### ISSUE TITLE
Script is not working

### ISSUE THREAD

**Issue by saadhossain** [ni554n/userscripts#2]
I have installed temparmonkey and installed your script but there is no Remove All Request Button in the Fiverr...

Its not working, could you please fix this?

**Comment by ni554n** [comment]
I just tested it. It is working as expected on my browser using [ViolentMonkey](https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag).
May be try with that.

**Comment by saadhossain** [comment]
yes, bro, it's working with Volentmonkey...
It's such a nice job.
thanks
